//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GifCapture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GifCapture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Region.
        /// </summary>
        public static string CaptureRegion {
            get {
                return ResourceManager.GetString("CaptureRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Screen.
        /// </summary>
        public static string CaptureScreen {
            get {
                return ResourceManager.GetString("CaptureScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Window.
        /// </summary>
        public static string CaptureWindow {
            get {
                return ResourceManager.GetString("CaptureWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorde Region.
        /// </summary>
        public static string RecordeRegion {
            get {
                return ResourceManager.GetString("RecordeRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorde Screen.
        /// </summary>
        public static string RecordeScreen {
            get {
                return ResourceManager.GetString("RecordeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorde Window.
        /// </summary>
        public static string RecordeWindow {
            get {
                return ResourceManager.GetString("RecordeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording:.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Saved:.
        /// </summary>
        public static string RecordingSaved {
            get {
                return ResourceManager.GetString("RecordingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Path:.
        /// </summary>
        public static string SavedPath {
            get {
                return ResourceManager.GetString("SavedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Saved.
        /// </summary>
        public static string ScreenshotSaved {
            get {
                return ResourceManager.GetString("ScreenshotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the screen to capture, or press Esc to cancel.
        /// </summary>
        public static string SelectScreenTip {
            get {
                return ResourceManager.GetString("SelectScreenTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the window to capture, or press Esc to exit.
        /// </summary>
        public static string SelectWindowTip {
            get {
                return ResourceManager.GetString("SelectWindowTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.redisant.com/gif.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
